# 
# Do not Edit! Generated by:
# spectacle version 0.14
# 
# >> macros
%define debug_package %{nil}
# << macros

Name:       aspell-en
Summary:    English dictionaries for Aspell
Version:    6.0
Release:    9
Group:      Applications/Text
License:    MIT and BSD
URL:        http://aspell.net/
Source0:    %{name}-%{version}.tar.gz
Source100:  aspell-en.yaml
Patch0:     aspell6-en-6.0-practise.patch
Requires:   aspell >= 0.60
BuildRequires:  aspell >= 0.60

%description
Provides the word list/dictionaries for the following: English, Canadian
English, British English




%prep
%setup -q -n %{name}-%{version}/aspell-en

# aspell6-en-6.0-practise.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
./configure
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%doc Copyright
%{_libdir}/aspell-0.60/*
# << files


